<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260301074217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ingredients comments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE ingredient_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, ingredient_id INT DEFAULT NULL, PRIMARY KEY (id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_954359AA933FE08C ON ingredient_comment (ingredient_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient_comment ADD CONSTRAINT FK_954359AA933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient DROP comment
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient_comment DROP CONSTRAINT FK_954359AA933FE08C
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ingredient_comment
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient ADD comment TEXT DEFAULT NULL
        SQL);
    }
}
