<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260301101525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Tag';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dish_tag (dish_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (dish_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_64FF4A98148EB0CB ON dish_tag (dish_id)');
        $this->addSql('CREATE INDEX IDX_64FF4A98BAD26311 ON dish_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B7835E237E06 ON tag (name)');
        $this->addSql('ALTER TABLE dish_tag ADD CONSTRAINT FK_64FF4A98148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dish_tag ADD CONSTRAINT FK_64FF4A98BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dish_tag DROP CONSTRAINT FK_64FF4A98148EB0CB');
        $this->addSql('ALTER TABLE dish_tag DROP CONSTRAINT FK_64FF4A98BAD26311');
        $this->addSql('DROP TABLE dish_tag');
        $this->addSql('DROP TABLE tag');
    }
}
