<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260301071455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial DB';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE dish (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) DEFAULT NULL,
              description TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              recipe_text TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE dish_ingredient (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              weight VARCHAR(255) DEFAULT NULL,
              comment TEXT DEFAULT NULL,
              dish_id INT NOT NULL,
              ingredient_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_77196056148EB0CB ON dish_ingredient (dish_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_77196056933FE08C ON dish_ingredient (ingredient_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE ingredient (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) DEFAULT NULL,
              comment TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_comment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              text TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              dish_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D8905C2C148EB0CB ON recipe_comment (dish_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              dish_ingredient
            ADD
              CONSTRAINT FK_77196056148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              dish_ingredient
            ADD
              CONSTRAINT FK_77196056933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              recipe_comment
            ADD
              CONSTRAINT FK_D8905C2C148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE dish_ingredient DROP CONSTRAINT FK_77196056148EB0CB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dish_ingredient DROP CONSTRAINT FK_77196056933FE08C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_comment DROP CONSTRAINT FK_D8905C2C148EB0CB
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE dish
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE dish_ingredient
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ingredient
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipe_comment
        SQL);
    }
}
